spring:
  application:
    name: API-GATEWAY    

okta:
  oauth2:
    issuer: https://dev-82131521.okta.com/oauth2/default
    audience: api://default
    client-id: 0oamp4h2rraFEpr455d7
    client-secret: G5m_Rq91JY_-B5L_e4JQ6th4HXOMcKmXjMeqmkgIY-cjgVzFuARBiv_LvBfYa9kF
    scopes: openid, profile, email, offline_access